// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvnswbnrdoexkwpxusyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2bnN3Ym5yZG9leGt3cHh1c3lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTY3NTYsImV4cCI6MjA3MzQzMjc1Nn0.hGUiUhs8Ww4l97ur1u7R3xykz-mkKp51_jTbHpE2yrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});